services:
  # Service MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./shared/db_data:/var/lib/mysql

  # Service pour la première application Symfony (api)
  api:
    build:
      context: ./docker/php
    depends_on:
      - mysql
      - kafka
    environment:
      DATABASE_URL: mysql://devuser:devpass@mysql:3306/api
    volumes:
      - ./api:/var/www
    expose:
      - "9000"

  # Service pour la deuxième application Symfony (app2)
  app2:
    build:
      context: ./docker/php
    depends_on:
      - mysql
      - kafka  
    environment:
      DATABASE_URL: mysql://devuser:devpass@mysql:3306/api
    volumes:
      - ./kafka-producer:/var/www
    expose:
      - "9001"

  # Service Nginx pour la première application Symfony (api)
  nginx-api:
    image: nginx:latest
    container_name: nginx-api
    volumes:
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www
    ports:
      - "8001:80"
    depends_on:
      - api
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
      

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 2181:2181
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - 9900:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - "kafka"

  phpmya:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: devuser
      PMA_PASSWORD: devpass
    depends_on:
      - mysql
    ports:
    - 8899:80 
 