framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                #options:
                #    auto_setup: true
            failed: 'doctrine://default?queue_name=failed'        
        routing:
            'App\Message\YourMessage': async
